### ISSUE TITLE
I don't understand how to get the dark theme

### ISSUE THREAD

**Issue by Sercurio** [Gioni06/terminal.css#37]
I didn't found any document for using the dark theme used on the demo website

**Comment by MaXFalstein** [comment]
In the ```<head>``` of the [Terminal CSS dark website], there is an extra ```<style>```:

```css
      :root {
        --global-font-size: 15px;
        --global-line-height: 1.4em;
        --global-space: 10px;
        --font-stack: Menlo, Monaco, Lucida Console, Liberation Mono,
          DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace,
          serif;
        --mono-font-stack: Menlo, Monaco, Lucida Console, Liberation Mono,
          DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace,
          serif;
        --background-color: #222225;
        --page-width: 60em;
        --font-color: #e8e9ed;
        --invert-font-color: #222225;
        --secondary-color: #a3abba;
        --tertiary-color: #a3abba;
        --primary-color: #62c4ff;
        --error-color: #ff3c74;
        --progress-bar-background: #3f3f44;
        --progress-bar-fill: #62c4ff;
        --code-bg-color: #3f3f44;
        --input-style: solid;
        --display-h1-decoration: none;
      }
```

This provides the dark theme.
I externally load the above CSS from a private CDN.
I will create a PR for this 🙂
